# Generated by Django 4.2.2 on 2024-01-13 01:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('number_of_keys_created', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_ID', models.CharField(max_length=4)),
                ('NTAG', models.CharField(default='', max_length=32)),
                ('NNSK', models.CharField(default='', max_length=16)),
                ('NNSKiv', models.CharField(default='', max_length=16)),
                ('NNSKsign', models.CharField(default='', max_length=16)),
                ('HMAC', models.CharField(default='', max_length=64)),
                ('device_id', models.CharField(default='', max_length=17, unique=True)),
                ('state', models.CharField(choices=[('unknown', 'Unknown'), ('requires_key', 'Requires Key'), ('ready_to_register', 'Ready to Register'), ('registered', 'Registered')], default='unknown', max_length=20)),
                ('generation_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppCA.keygeneration')),
            ],
        ),
    ]
