# Generated by Django 4.2.2 on 2024-01-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='device_id',
            field=models.CharField(default='', max_length=17),
        ),
    ]
